weights: yolov5l-xs-2.pt
cfg: models/yolov5l-xs-tr-ca-carafe-spp-bifpn.yaml
data: data/VisDrone.yaml
hyp: data/hyps/hyp.VisDrone.yaml
epochs: 320
batch_size: 32
imgsz: 416
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 0
project: runs/train
name: train_slice_ca_carafe_
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: 5
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/train_slice_ca_carafe_
